### PR TITLE
Fixed ie11 positioning fixes #31

### LINKED ISSUE #31: positioning in IE 11 not working
The inline styles of the popover container element always have `left` and `top` set to `0`.

I'm investigating why this is., any help would be appreciated!

Really loving this component!

### PR DESCRIPTION
**Pull request by juliankrispel**
- [x] fallback to pageXOffset and documentElement.scroll
- [x] upgraded react-draggable for demo (there were tons of warnings)

sep 02 2015 14 07

### CODE REVIEW

**Comment by jasonkuhrt** [comment]
@juliankrispel First off, thank-you very much for this. I'm going to review the code and ask some questions along the way. We should be able to get this merged and released today.

File: lib/layout.js [hunk 1]
```diff
@@ -215,8 +215,10 @@ El.calcSize = (el) => (
 
 El.calcScrollSize = (el) => (
   el === window
-    ? { w: el.scrollX, h: el.scrollY }
-    : { w: el.scrollLeft, h: el.scrollTop }
+   ? {
+    w: el.scrollX || el.pageXOffset || document.documentElement.scrollLeft,
+    h: el.scrollY || el.pageYOffset || document.documentElement.scrollTop
```
Comment (jasonkuhrt) [inline lib/layout.js]: Why would you reach out to the `html` element? And assuming there is a valid reason I'm not sure I like this approach. This was intentionally a pure function before [1].

[1] Excepting the "type" check on `el`

File: package.json [hunk 2]
```diff
@@ -27,24 +27,24 @@
...
-    "react-tappable": "^0.5.1",
-    "babel-loader": "^4.2.0",
-    "ramda": "^0.14.0",
-    "webpack-dev-server": "^1.8.0",
+    "coffee-script": "^1.9.1",
     "css-loader": "^0.9.1",
     "object.assign": "^1.1.1",
+    "ramda": "^0.14.0",
     "react": "^0.13.1",
-    "react-draggable": "^0.4.0"
```
Comment (jasonkuhrt) [inline package.json]: Can you explain this. My scan did not catch any other version changes but please confirm in case I'm wrong. Thanks.

File: lib/layout.js (hunk 1 above)
Comment (juliankrispel) [inline lib/layout.js]: for more browser coverage, [see here](https://developer.mozilla.org/en-US/docs/Web/API/Window/scrollY?redirectlocale=en-US&redirectslug=DOM%2Fwindow.scrollY)

File: package.json (hunk 2 above)
Comment (juliankrispel) [inline package.json]: This fixed the example breaking (I said this in the pr description btw)

**Comment by juliankrispel** [comment]
Thanks for the review @jasonkuhrt :+1:

File: lib/layout.js (hunk 1 above)
Comment (jasonkuhrt) [inline lib/layout.js]: I misread my own function pardon me; right we are resolving the check for `window` in this case not `el`.

This component uses `flexbox` and inline `svg` so unless you can find a browser that supports those but not  `pageX/YOffset` I am asking for that third fallback to be removed. Of course I'm happy to accept the `pageX/YOffset` fallback though. Make sense?

Comment (juliankrispel) [inline lib/layout.js]: makes total sense :) I'll make the changes

**Comment by juliankrispel** [comment]
@jasonkuhrt adjusted the pr! :heart:

**Comment by jasonkuhrt** [comment]
@juliankrispel Thanks. Regarding the demo though I need to know more a bit more because I'm not seeing the issue. When I open http://littlebits.github.io/react-popover/build/  in Chrome I do not see an issue in the logs. What am I missing?

**Comment by juliankrispel** [comment]
@jasonkuhrt try a fresh install, that should reproduce it

**Comment by juliankrispel** [comment]
@jasonkuhrt sry for the delayed response

**Comment by jasonkuhrt** [comment]
No problem, checking it out now.

**Comment by jasonkuhrt** [comment]
I saw the issue and am fixing now. Very strange. Please remove the fix from your PR as its unrelated to support for ie11. None the less thanks for bringing attention to this other issue!

**Comment by juliankrispel** [comment]
@jasonkuhrt done

**Comment by jasonkuhrt** [comment]
Awesome thanks again for seeing this through to completion.

**Comment by juliankrispel** [comment]
@jasonkuhrt pleasure :-)

**Comment by jasonkuhrt** [comment]
@juliankrispel Cut https://github.com/littlebits/react-popover/releases/tag/v0.3.5
