### PR TITLE
Fix createClass deprecation warnings using createReactClass package

### LINKED ISSUE #100: Deprecated React.createClass and React.PropTypes
React.createClass and React.PropTypes are deprecated from react 15.5., which causes errors in console.

### PR DESCRIPTION
**Pull request by AlexNisnevich**
Fixes #100.

### CODE REVIEW

File: examples/rows/main.js [hunk 1]
```diff
@@ -1,6 +1,7 @@
 import "./main.css"
 import F from "ramda"
 import React, { DOM as E } from "react"
+import createReactClass from "create-react-class"
```
Comment (jasonkuhrt) [inline examples/rows/main.js]: Line 49 also needed replacement.
